"""add achieved column to goals table

Revision ID: 2cfec564d8ee
Revises: 0ecd3e1d531c
Create Date: 2016-06-05 01:19:51.831351

"""

# revision identifiers, used by Alembic.
revision = '2cfec564d8ee'
down_revision = '0ecd3e1d531c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('achieved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'achieved')
    ### end Alembic commands ###
