"""Task model added

Revision ID: 3fa608acf1f3
Revises: bc9730080bb5
Create Date: 2016-03-03 15:00:23.539279

"""

# revision identifiers, used by Alembic.
revision = '3fa608acf1f3'
down_revision = 'bc9730080bb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('task_title', sa.String(length=128), nullable=True),
    sa.Column('set_time', sa.Integer(), nullable=True),
    sa.Column('remained_time', sa.Integer(), nullable=True),
    sa.Column('serial_passed_time', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_timestamp'), 'tasks', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_timestamp'), table_name='tasks')
    op.drop_table('tasks')
    ### end Alembic commands ###
