"""add achieved column to goals table

Revision ID: 9586d8126d80
Revises: 4509fc186294
Create Date: 2016-06-05 05:16:27.303103

"""

# revision identifiers, used by Alembic.
revision = '9586d8126d80'
down_revision = '4509fc186294'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('achieved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'achieved')
    ### end Alembic commands ###
