"""User confired column added

Revision ID: b0d413c4b09b
Revises: c2420b67e439
Create Date: 2016-02-27 22:32:05.488219

"""

# revision identifiers, used by Alembic.
revision = 'b0d413c4b09b'
down_revision = 'c2420b67e439'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
