"""user since and last_seen column added

Revision ID: bc9730080bb5
Revises: b0d413c4b09b
Create Date: 2016-03-03 11:44:21.847494

"""

# revision identifiers, used by Alembic.
revision = 'bc9730080bb5'
down_revision = 'b0d413c4b09b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###
