"""auth func added

Revision ID: c2420b67e439
Revises: 2c18c124c1d8
Create Date: 2016-02-26 15:48:45.192669

"""

# revision identifiers, used by Alembic.
revision = 'c2420b67e439'
down_revision = '2c18c124c1d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
